---
default: true

# default indent = 4 spaces
MD007:
  indent: 2

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 149
  # Number of characters for headings
  heading_line_length: 119
  # Number of characters for code blocks
  code_block_line_length: 199
  # Include code blocks
  code_blocks: true
  # Ignore table length violations
  tables: false
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

MD024:
  # Allow heading duplication if under different parent headings
  siblings_only: true

# mkdocs allows ordered lists with its own style
MD029: false

# Our documentation uses sections with prerequisite/procedure pairs
# that will end up with having duplicate headers sections.
MD036: false

# mkdocs uses indentation for notes block
MD046: false
